apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxysql
spec:
  serviceName: "proxysql"
  replicas: 1
  selector:
    matchLabels:
      front: proxysql
  template:
    metadata:
      labels:
        app: proxysql
        front: proxysql
    spec:
      securityContext:
        fsGroup: 1000140000
      containers:
      - name: proxysql
        image:  perconalab/proxysql-openshift
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 6032
          name: proxyadm
        volumeMounts:
        - name: proxydata
          mountPath: /var/lib/proxysql
          subPath: data
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: root
        - name: MYSQL_PROXY_USER
          value: "proxyuser"
        - name: MYSQL_PROXY_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: proxyuser
        - name: SERVICE
          value: percona-xtradb-cluster
        lifecycle:
          postStart:
            exec:
              command: 
              - "/usr/bin/peer-list"
              - -on-start="/usr/bin/add_cluster_nodes.sh"
              - -service=replicaset1 # name of the service running ReplicaSet  StatefulSet
  volumeClaimTemplates:
  - metadata:
      name: proxydata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxysql
  name: sql
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: proxyadm
      port: 6032
      protocol: TCP
      targetPort: 6032
  selector:
    app: proxysq
