apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pxccluster1
  labels:
    app: percona-xtradb-cluster
spec:
  ports:
  - port: 3306
    name: mysql-port
  clusterIP: None
  selector:
    app: percona-xtradb-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pxcnode
spec:
  selector:
    matchLabels:
      app: percona-xtradb-cluster
  serviceName: "pxccluster1"
  replicas: 3
  template:
    metadata:
      labels:
        app: percona-xtradb-cluster
    spec:
      securityContext:
        fsGroup: 1000140000
      containers:
      - name: mysql
        image:  perconalab/pxc-openshift
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 4444
          name: sst
        - containerPort: 4567
          name: replication
        - containerPort: 4568
          name: ist
        readinessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          initialDelaySeconds: 15
          timeoutSeconds: 15
          periodSeconds: 30
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          initialDelaySeconds: 300
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
          subPath: data
        - name: config-volume
          mountPath: /etc/mysql/conf.d/
        env:
          - name: MYSQL_FORCE_INIT
            value: "1"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: root
          - name: XTRABACKUP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: xtrabackup
          - name: MONITOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: monitor
          - name: CLUSTERCHECK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: clustercheck
      volumes:
      - name: config-volume
        configMap:
          name: mysql
          optional: true
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
